manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

    - name: antmicro
      url-base: https://github.com/antmicro

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.2-branch
      import:
        path-allowlist:
          - modules/debug/*
          - modules/hal/*
          - modules/lib/*
          - modules/tee/tf-m/*

    # TODO: investigate why adding tflite-micro to above import list does not work
    - name: tflite-micro
      remote: zephyrproject-rtos
      revision: zephyr-v4.1.0

    - name: emlearn
      url: https://github.com/emlearn/emlearn
      revision: master

    - name: kenning-zephyr-runtime
      url: https://github.com/antmicro/kenning-zephyr-runtime/
      revision: main
      import:
        path-allowlist:
          - dlpack
          - tvm

