name: Pre-commit linting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          sudo apt update -qqy
          sudo apt install -qqy curl git clang-format-19
      - name: Run pre-commit
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          export PATH=$HOME/.local/bin:$PATH
          sudo ln -sf /usr/bin/clang-format-19 /usr/bin/clang-format
          uvx pre-commit run --all-files
